version: '3.2'
services:
  db:
    image: postgres:10.18-bullseye
    environment:
      - POSTGRES_DB=hitech_apd_test
      - POSTGRES_PASSWORD=cms
    expose:
      - 5432
    ports:
      - '55432:5432'

  mongo:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin-user
      - MONGO_INITDB_ROOT_PASSWORD=admin-password
      - MONGO_INITDB_DATABASE=admin
      - MONGO_DATABASE_USERNAME=mongo-test
      - MONGO_DATABASE_PASSWORD=cms-test
      - MONGO_DATABASE=eapd-test
    volumes:
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    command: [--auth]
    ports:
      - 27018:27017

  api-for-testing:
    build: .
    image: cms-eapd/api
    depends_on:
      - db
      - mongo
    environment:
      - PORT=8000
      - NODE_ENV=test
      - API_PORT=8000
      - API_HOST=api-for-testing
      - ENDPOINT_COVERAGE_CAPTURE=true
      - MONGO_ADMIN_URL=mongodb://admin-user:admin-password@mongo:27017/admin
      - MONGO_URL=mongodb://mongo-test:cms-test@mongo:27017/eapd-test?authSource=admin
      - MONGO_DATABASE=eapd-test
      - FILE_STORE=local
      - FILE_PATH=test-data/files
      - OKTA_DOMAIN=${OKTA_DOMAIN}
      - OKTA_SERVER_ID=${OKTA_SERVER_ID}
      - OKTA_CLIENT_ID=${OKTA_CLIENT_ID}
      - OKTA_API_KEY=${OKTA_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    command: yarn start
    expose:
      - 8000
    volumes:
      - ./:/app
      - /app/node_modules
