version: "3"
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=hitech_apd_test
      - POSTGRES_PASSWORD=cms
    expose:
      - 5432

  api-for-testing:
    image: cms-eapd/api:fbf4381fe1bf916b6a5d262ad4f717fe
    depends_on:
      - db
    environment:
      - AUTH_LOCK_FAILED_ATTEMPTS_COUNT=5
      - AUTH_LOCK_FAILED_ATTEMPTS_WINDOW_TIME_MINUTES=1
      - AUTH_LOCK_FAILED_ATTEMPTS_DURATION_MINUTES=30
      - PORT=8000
      - NODE_ENV=test
      - API_PORT=8000
      - API_HOST=api-for-testing
      - ENDPOINT_COVERAGE_CAPTURE=yes
      - STORE_TYPE=fs
      - STORE_PATH=test-data/files
    command: npm start
    expose:
      - 8000
    volumes:
      - ./:/app
      - /app/node_modules
