name: Cleanup Test/Preview Deploys
on:
  push: 
    branches: bbrooks/environment_vulnerability_scans
#  schedule:
#    - cron: '0 0 * * *'  # Run every hour, every day
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Preview    
    timeout-minutes: 60    
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
    - name: Checkout Repo ğŸ›ï¸
      uses: actions/checkout@v2
    - name: Configure AWS Credentials â˜ï¸
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}   
    - name: Set up Python ${{ matrix.python-version }} ğŸ
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies ğŸ’¿
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install jq -y
        pip install --quiet awscli
    - name: Cleanup Test/Preview Deploys w/No Open PR ğŸš¿
      env:
        API_AWS_REGION: ${{ secrets.AWS_REGION }}
        GH_BOT_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_BOT_USER: ${{ secrets.GH_BOT_USER }}
      run: |
        ./bin/preview-deploy/aws.cleanup.sh \
