name: Cypress Tests
on:
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
  push:
    branches:
      - bbrooks/3227-Cypress-CI

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - name: Cache Node Modules ğŸ’¾
        uses: actions/cache@v2
        with:
          path: ./.npm
          key: cms-hitech-apd-npm-{{ checksum "web/package-lock.json" }}-{{ checksum "api/package-lock.json" }}
          restore-keys: cms-hitech-apd-npm-{{ checksum "web/package-lock.json" }}-{{ checksum "api/package-lock.json" }}

      - name: Checkout Repo ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install Web Dependencies ğŸ•¸ï¸
        working-directory: ./web
        run: |
          npm ci
      - name: Upload Frontend Node Modules ğŸ•¸ï¸
        uses: actions/upload-artifact@v2
        with:
          name: frontend-modules
          path: web/node_modules

      - name: Install API Dependencies âœ¨
        working-directory: ./api
        run: |
          npm ci
      - name: Upload Backend Node Modules âœ¨
        uses: actions/upload-artifact@v2
        with:
          name: backend-modules
          path: web/node_modules


  dependency-vulnerability-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - name: Retrieve Cached Frontend Modules
        uses: actions/download-artifact@v2
        with:
          name: frontend-modules
      - name: Frontend Vulnerability Scan ğŸ•¸ï¸
        working-directory: ./web
        run: |
          npm run audit
    
      - name: Retrieve Cached Backend Modules
        uses: actions/download-artifact@v2
        with:
          name: backend-modules
      - name: Backend Vulnerability Scan âœ¨
        working-directory: ./api
        run: |
          npm run audit
    needs: install-dependencies

  cypress-run-headless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
    needs: install-dependencies
