name: Cypress Tests
on:
#  schedule:
#    - cron: '0 0 * * *'  # every day at midnight
  push:
    branches:
      - bbrooks/3227-Cypress-CI

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - name: Checkout Repo ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install Web Dependencies ğŸ•¸ï¸
        working-directory: ~/web
        run: |
          npm ci
      - name: Install API Dependencies âœ¨
        working-directory: ~/api
        run: |
          npm ci

  cypress-run-headless:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
