name: Cleanup Plantinum AMIs
on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  push:
    branches:
      - bbrooks/3510-Packer_Secrets    
jobs:
  packer-ami-cleanup:
    runs-on: ubuntu-latest
    environment: Preview    
    timeout-minutes: 60    
    steps: 
      - name: Checkout Repo ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Configure AWS Credentials â˜ï¸
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}   
      - name: Clean Up Old AMIs ğŸ§¹
        run: | 
          ./bin/preview-deploy/aws.amicleanup.sh
